name: Deployer la documentation d'API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Générer la documentation d'API
      run: ./gradlew dokkaHtml --no-daemon
    - name: Corriger les permissions
      working-directory: ./SujetBD/build/dokka/html
      run: |
        chmod -c -R +rX "./" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./SujetBD/build/dokka/html
        name: github-pages

  deploy:
    name: Déployer le site
    needs: build

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4