name: Deployer la documentation d'API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build
      id: build
      run: |
        if ! ./gradlew build; then
          # Address a rare unit test failure very likely to be a test-harness-related
          # race condition.
          echo "Build failed, retrying once"
          if ! ./gradlew build; then
            exit 1
          fi
        fi
    - name: Générer la documentation d'API
      run: ./gradlew dokkaHtml
    - name: Upload artifact
      uses: actions/upload-artifact@v4

  deploy:
    name: Déployer le site
    needs: build

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4