name: Deployer la documentation d'API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Générer la documentation d'API
      run: ./gradlew dokkaHtml
    - name: testy
      run: ls SujetBD/build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./SujetBD/build/documentation/html

  deploy:
    name: Déployer le site
    needs: build

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Déploiement
        id: deployment
        uses: actions/deploy-pages@v4